color.show <- function(x, show.help = F) {
  if (show.help) {
    stop("x can be a character vector of hex, or a vector of rgb objects generated by rgb()")
  }
  df <- data.frame(x = 1:length(x), y = 1, fill = factor(1:length(x)))
  p <- ggplot(df, aes(x = x, y = y, fill = fill)) +
    geom_tile() +
    scale_fill_manual(values = x) +
    theme_void()+
    theme(legend.position="none")
  return(p)
}
color.hue.fc <- function(n, palette = "R4.fc1") {
  palettes <- list(
    R4 = c("#CD0BBC", "#F5C710", "#2297E6", "#61D04F", "#DF536B",  "#28E2E5", "black", "gray62"),
    R4.fc1 = c("#CD0BBC", "#F8766D", "#F5C710", "#2297E6", "#61D04F",
               "#DF536B",  "#28E2E5", "black", "gray62"),
    R4.fc2 = c("#2297E6", "#F5C710", "#61D04F", "#CD0BBC", "#F8766D",
               "#DF536B",  "#28E2E5", "black", "gray62"),
    red_green = c("orangered", "#00BFC4"),
    black_yellow = c("black", "#F5C710"))
  # R4.fc1 is basically R4, but with the ggplot2 default red added in...

  if (!palette %in% names(palettes)) {
    stop(paste0("palette ", palette, " not found"))
  }
  colors <- palettes[[palette]]
  if (n > length(colors)) {
    stop("not enough colors in the palette")
  } else {
    return(colors[1:n])
  }
}


gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}


gg.color.keeplevel <- function(fac.vec) {
  # input is a factor vector.
  # this is to combat the default behaviour of ggplot2: it drops the empty levels and re-factors the input,
  # which messes up the correspondance between cell clusters and colors
  if (!is.factor(fac.vec)) {
    stop("!is.factor(fac.vec)")
  }
  levels <- levels(fac.vec)
  n.levels <- length(levels)
  cols <- utilsFanc::gg_color_hue(n = n.levels)
  levels.avail <- as.numeric(fac.vec) %>% unique() %>% sort()
  cols <- cols[levels.avail]
  return(cols)
}
